// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNHw8hl30tvGqBUSPmXmvk3eJ_53oL3-o',
    appId: '1:200640869247:web:190d07a8a9a0cb48d2204a',
    messagingSenderId: '200640869247',
    projectId: 'tutorconnect-333e4',
    authDomain: 'tutorconnect-333e4.firebaseapp.com',
    storageBucket: 'tutorconnect-333e4.firebasestorage.app',
    measurementId: 'G-GF58Y8YGH3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOGKRPJPNmuHCS_IDMAbHQ7zzze3HzMYQ',
    appId: '1:200640869247:android:5d0b7a6d8ec3edb0d2204a',
    messagingSenderId: '200640869247',
    projectId: 'tutorconnect-333e4',
    storageBucket: 'tutorconnect-333e4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDw1120N5e6HGPW4QWw-XwnxeGwpdQ2qSo',
    appId: '1:200640869247:ios:c5cb078ca56f981ad2204a',
    messagingSenderId: '200640869247',
    projectId: 'tutorconnect-333e4',
    storageBucket: 'tutorconnect-333e4.firebasestorage.app',
    iosBundleId: 'com.example.tutorConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDw1120N5e6HGPW4QWw-XwnxeGwpdQ2qSo',
    appId: '1:200640869247:ios:c5cb078ca56f981ad2204a',
    messagingSenderId: '200640869247',
    projectId: 'tutorconnect-333e4',
    storageBucket: 'tutorconnect-333e4.firebasestorage.app',
    iosBundleId: 'com.example.tutorConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNHw8hl30tvGqBUSPmXmvk3eJ_53oL3-o',
    appId: '1:200640869247:web:b25b9c68f972b21ad2204a',
    messagingSenderId: '200640869247',
    projectId: 'tutorconnect-333e4',
    authDomain: 'tutorconnect-333e4.firebaseapp.com',
    storageBucket: 'tutorconnect-333e4.firebasestorage.app',
    measurementId: 'G-J2NCKGXMEE',
  );

}